export const SYMBOLS = {
  // Infrastructure
  PathResolverService: Symbol.for("PathResolverService"),
  LoggerService: Symbol.for("LoggerService"),
  SecretService: Symbol.for("SecretService"),
  DatabaseService: Symbol.for("DatabaseService"),
  ConfigRepository: Symbol.for("ConfigRepository"),
  MigrationService: Symbol.for("MigrationService"),
  VersionManager: Symbol.for("VersionManager"),
  UpdateWorkerService: Symbol.for("UpdateWorkerService"),
  AppConfig: Symbol.for("AppConfig"),
  LifecycleManager: Symbol.for("LifecycleManager"),

  // System
  SessionService: Symbol.for("SessionService"),
  WindowService: Symbol.for("WindowService"),
  TrayService: Symbol.for("TrayService"),
  UIService: Symbol.for("UIService"),
  HttpServerService: Symbol.for("HttpServerService"),
  StaticAssetService: Symbol.for("StaticAssetService"),
  RouteRegistry: Symbol.for("RouteRegistry"),
  McpFacade: Symbol.for("McpFacade"),
  ProjectIdentityService: Symbol.for("ProjectIdentityService"),
  MasterSingletonService: Symbol.for("MasterSingletonService"),
  McpDiscoveryService: Symbol.for("McpDiscoveryService"),
  PortOwnershipService: Symbol.for("PortOwnershipService"),
  IMRuntimeOrchestrator: Symbol.for("IMRuntimeOrchestrator"),
  McpSSEBridgeService: Symbol.for("McpSSEBridgeService"),

  // IM
  IMProvider: Symbol.for("IMProvider"),
  IMPluginRegistry: Symbol.for("IMPluginRegistry"),
  IMFacade: Symbol.for("IMFacade"),
  IMWebhookIngressService: Symbol.for("IMWebhookIngressService"),
  IMAdminCaptureService: Symbol.for("IMAdminCaptureService"),
  IMBindingService: Symbol.for("IMBindingService"),

  // Message
  MessageCoreService: Symbol.for("MessageCoreService"),
  MessageOutboxService: Symbol.for("MessageOutboxService"),
  MessageManagerStore: Symbol.for("MessageManagerStore"),
  MessageEvents: Symbol.for("MessageEvents"),
  RoutingKernelService: Symbol.for("RoutingKernelService"),

  ConversationQueryService: Symbol.for("ConversationQueryService"),
  SessionApplicationService: Symbol.for("SessionApplicationService"),
  ProjectStore: Symbol.for("ProjectStore"),
  McpSessionBindingStore: Symbol.for("McpSessionBindingStore"),
  ProjectModeStore: Symbol.for("ProjectModeStore"),
  MemoryStore: Symbol.for("MemoryStore"),
  RouteStore: Symbol.for("RouteStore"),
  ProjectModeFacade: Symbol.for("ProjectModeFacade"),
  ProjectModeStatusService: Symbol.for("ProjectModeStatusService"),
  ToolRegistryService: Symbol.for("ToolRegistryService"),
  ChannelDriverRegistry: Symbol.for("ChannelDriverRegistry"),
  ChannelFacade: Symbol.for("ChannelFacade"),
  McpIdeChannelDriver: Symbol.for("McpIdeChannelDriver"),
  CodexCliChannelDriver: Symbol.for("CodexCliChannelDriver"),
  CloudCodeCliChannelDriver: Symbol.for("CloudCodeCliChannelDriver"),
  OrchestratorReservedChannelDriver: Symbol.for("OrchestratorReservedChannelDriver"),
  HarnessTelemetryService: Symbol.for("HarnessTelemetryService"),
  HarnessExecutionService: Symbol.for("HarnessExecutionService"),
  HarnessEvaluationService: Symbol.for("HarnessEvaluationService"),
  HarnessReplayService: Symbol.for("HarnessReplayService"),
  HarnessGateService: Symbol.for("HarnessGateService"),
  HarnessStore: Symbol.for("HarnessStore"),
  HarnessQueryService: Symbol.for("HarnessQueryService"),
  HarnessFailureClassifierService: Symbol.for("HarnessFailureClassifierService"),
  MemoryCoreService: Symbol.for("MemoryCoreService"),

  // Other
  StreamSnapshotService: Symbol.for("StreamSnapshotService"),
  MetricsService: Symbol.for("MetricsService"),
  ProjectContextService: Symbol.for("ProjectContextService"),
  UsecaseBus: Symbol.for("UsecaseBus"),

  SwitchProjectModeUsecase: Symbol.for("SwitchProjectModeUsecase"),
  SwitchProjectChannelUsecase: Symbol.for("SwitchProjectChannelUsecase"),
  StartMcpServerUsecase: Symbol.for("StartMcpServerUsecase"),
  SetupSSESessionUsecase: Symbol.for("SetupSSESessionUsecase"),
  EnsureProjectModeAllowsMessageUsecase: Symbol.for("EnsureProjectModeAllowsMessageUsecase"),
  SendMessageUsecase: Symbol.for("SendMessageUsecase"),
  ValidateWebhookUsecase: Symbol.for("ValidateWebhookUsecase"),
  CreateOrBindGroupUsecase: Symbol.for("CreateOrBindGroupUsecase"),
  IngestIMMessageUsecase: Symbol.for("IngestIMMessageUsecase"),

  // API Controllers
  IMController: Symbol.for("IMController"),
  SessionController: Symbol.for("SessionController"),
  SystemController: Symbol.for("SystemController"),
  MonitorController: Symbol.for("MonitorController"),
  ProjectModeController: Symbol.for("ProjectModeController"),
  ChannelController: Symbol.for("ChannelController"),
  HarnessController: Symbol.for("HarnessController")
};
